### ISSUE TITLE
capa 2.0 can't load properly on saltstack v2021.29.4

### ISSUE THREAD

**Issue by davidep** [REMnux/remnux-cli#38]
I'm getting execution error with the latest capa 2.0 pulled via saltstack v2021.29.4

```
ERROR:capa:default embedded rules not found! (maybe you installed capa as a library?)
ERROR:capa:provide your own rule set via the `-r` option.
ERROR:capa:rule path (embedded rules) does not exist or cannot be accessed
```

after manually providing the path to the rules under /usr/local/share/capa-rules/ I get this different error:
loading : 
```
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 580/580 [00:00<00:00, 1629.41 rules/s]
Traceback (most recent call last):
  File "/usr/local/bin/capa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/capa/main.py", line 886, in main
    pure_file_capabilities, _ = find_file_capabilities(rules, file_extractor, {})
  File "/usr/local/lib/python3.6/dist-packages/capa/main.py", line 114, in find_file_capabilities
    for feature, va in extractor.extract_file_features():
  File "/usr/local/lib/python3.6/dist-packages/capa/features/extractors/pefile.py", line 148, in extract_file_features
    for feature, va in extract_file_features(self.pe, self.path):
  File "/usr/local/lib/python3.6/dist-packages/capa/features/extractors/pefile.py", line 124, in extract_file_features
    for feature, va in file_handler(pe, file_path):
  File "/usr/local/lib/python3.6/dist-packages/capa/features/extractors/pefile.py", line 36, in extract_file_export_names
    name = export.name.partition(b"\x00")[0].decode("ascii")
AttributeError: 'NoneType' object has no attribute 'partition'
```

This is on an Ubuntu 18.04

Any idea what can be the issue?

**Comment by lennyzeltser** [comment]
@davidep, Thanks for reporting the issue. It looks like it was due to the change in version 2.0 of capa, which wasn't reflected in the way REMnux was installing the tool.

I believe I corrected the issue. Please run `remnux upgrade` and reboot. Let me know if it's been fixed, please.

**Comment by davidep** [comment]
@lennyzeltser 
now I'm getting the same error I was getting by manually providing the path to the rules

```
loading : 100%|█████████████████████████| 579/579 [00:00<00:00, 2704.27 rules/s]
Traceback (most recent call last):
  File "main.py", line 1004, in <module>
  File "main.py", line 886, in main
  File "main.py", line 114, in find_file_capabilities
  File "features/extractors/pefile.py", line 148, in extract_file_features
  File "features/extractors/pefile.py", line 124, in extract_file_features
  File "features/extractors/pefile.py", line 36, in extract_file_export_names
AttributeError: 'NoneType' object has no attribute 'partition'
[7798] Failed to execute script main
```

**Comment by lennyzeltser** [comment]
Hmm... I'm at a loss, and unable to reproduce the problem on my side.

I'm curious... Does the issue occur with the capa binary you can download directly [from the capa Github repo](https://github.com/fireeye/capa/releases/tag/v2.0.0)?

The direct link is:
https://github.com/fireeye/capa/releases/download/v2.0.0/capa-v2.0.0-linux.zip

**Comment by lennyzeltser** [comment]
Also, I'm wondering whether the issue is specific to the file you're examining?

Does the following work for you:

```
capa /var/lib/inetsim/http/fakefiles/sample_gui.exe
```

**Comment by davidep** [comment]
Interesting the issue is only with a sample of NotPetya that used to work with capa 1.6 
Also the same issue is with the original capa 2.0 from github, so definitely not anymore related to the remnux saltstack.
I opened this one https://github.com/fireeye/capa/issues/684 
For the record the test was done with sample MD5: 71b6a493388e7d0b40c83ce903bc6b04

So yes no issues with other samples. sorry for the little testing before posting the update
Thanks a lot Lenny!

**Comment by lennyzeltser** [comment]
Your issue helped me spot a problem that's now fixed for all REMnux users, so thank you for your report!
